print("Create your charater")
name = input("What is your charater called?")
age = input("What is your charater's age?")
strengths = input("What is your charater's Strength")
weaknesses = input("What is your charaters's Weaknesses")
print("Your charater's name is", name)
print("Your charater is", age, "years old")
print("Strengths:", strengths)
print("Weaknesses:", weaknesses)
print(name, "says, 'Thanks for creating me!'")
